### ISSUE TITLE
Aliases still carry .coffee extension

### ISSUE THREAD

**Issue by bergie** [anthonyshort/component-coffee#3]
I'm using your plugin with [NoFlo](https://github.com/bergie/noflo).

When built as standalone, the CoffeeScript files get translated and renamed correctly.

However, when using my package as a dependency, it does work because the require aliases still carry .coffee suffixes:

```
require.alias("bergie-noflo/src/components/Graph.coffee", "noflo-dataflow/deps/noflo/src/components/Graph.coffee");
require.alias("bergie-noflo/src/components/Output.coffee", "noflo-dataflow/deps/noflo/src/components/Output.coffee");
require.alias("bergie-noflo/src/lib/NoFlo.js", "noflo-dataflow/deps/noflo/index.js");
require.alias("component-emitter/index.js", "bergie-noflo/deps/emitter/index.js");
```

**Comment by bergie** [comment]
Quick workaround is to do a search-replace in the built file before using it. Here is how I'm doing that in my Grunt setup using [grunt-combine](https://github.com/mcgaryes/grunt-combine):

```
combine:
  browser:
    input: 'dist/dataflo.js'
    output: 'dist/dataflo.js'
    tokens: [
      token: '.coffee'
      string: '.js'
    ]
```
